{{- if or .Values.Common.IngressSecrete.AutoCreate  .Values.Common.PersistenVolumeClaim.AutoCreate }}
apiVersion: batch/v1
kind: Job
metadata:
  name: wcs-pre-install-{{ .Values.Common.Tenant | lower}}{{ .Values.Common.EnvironmentName | lower}}{{ .Values.Common.EnvironmentType }}-{{ randAlphaNum 10 | lower }}
  namespace: {{ .Values.Common.NameSpace }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-delete-policy": "hook-succeeded"
    "helm.sh/hook-delete-policy": "before-hook-creation"
spec:
  backoffLimit: 5
  activeDeadlineSeconds: 100
  template:
    spec:
      restartPolicy: Never   
      containers:
      {{- if .Values.Common.IngressSecrete.AutoCreate }}
        - name: pre-install-job-createsecret-{{ .Values.Common.Tenant | lower}}{{ .Values.Common.EnvironmentName | lower}}{{ .Values.Common.EnvironmentType }}-{{ randAlphaNum 10 | lower }}
          image: {{ .Values.Common.ImageRepo }}{{ .Values.SupportC.Image }}:{{ .Values.SupportC.Tag }}
          args: ['createsecret', '-tenant',{{ .Values.Common.Tenant }},'-env',{{ .Values.Common.EnvironmentName}},'-envtype',{{ .Values.Common.EnvironmentType }},'-namespace',{{ .Values.Common.NameSpace }},'-replace','true']
      {{- end -}}
      {{- if .Values.Common.PersistenVolumeClaim.AutoCreate }}
        - name: pre-install-job-createpvc-{{ .Values.Common.Tenant | lower}}{{ .Values.Common.EnvironmentName | lower}}{{ .Values.Common.EnvironmentType }}-{{ randAlphaNum 10 | lower }}
          image: {{ .Values.Common.ImageRepo }}{{ .Values.SupportC.Image }}:{{ .Values.SupportC.Tag }}
          args: ['createpvc', '-tenant',{{ .Values.Common.Tenant | quote }},'-env',{{ .Values.Common.EnvironmentName | quote }},'-envtype',{{ .Values.Common.EnvironmentType }},'-namespace',{{ .Values.Common.NameSpace | quote }},'-component','search','-storage_class',{{ .Values.Common.PersistenVolumeClaim.StorageClass | quote }},'-access_modes',{{ .Values.Common.PersistenVolumeClaim.AccessModes | quote }},'-storage_size',{{ .Values.Common.PersistenVolumeClaim.StorageSize | quote }},'-force',{{ .Values.Common.PersistenVolumeClaim.Force | quote }}]
      {{ end -}}
{{ end -}}
