apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.Common.Tenant }}{{ .Values.Common.EnvironmentName}}{{ .Values.Common.EnvironmentType }}{{.Values.Tsweb.Name}}
  namespace: {{ .Values.Common.NameSpace }}
spec:
  replicas: {{ .Values.Tsweb.Replica }}
  template:
    metadata:
      labels:
        component: {{ .Values.Common.Tenant }}{{ .Values.Common.EnvironmentName}}{{ .Values.Common.EnvironmentType }}{{.Values.Tsweb.Name}}
        group: {{ .Values.Common.Tenant }}{{ .Values.Common.EnvironmentName}}{{ .Values.Common.EnvironmentType }}
    spec:
      initContainers:
      - name: transaction-web-dependence-check
        image: "{{ .Values.Common.ImageRepo }}{{ .Values.SupportC.Image }}:{{ .Values.SupportC.Tag }}"
        imagePullPolicy: IfNotPresent
        args: ['depcheck', '-component','transaction-web','-tenant',{{ .Values.Common.Tenant }},'-env',{{ .Values.Common.EnvironmentName}},'-envtype',{{ .Values.Common.EnvironmentType }},'-namespace',{{ .Values.Common.NameSpace }},'-interval_time','20','-expect_during_time','600','-timeout','5','-spiuser_pwd_encrypte',{{ .Values.Common.SPIUserPWDBase64 }}]
      volumes:
        - name: logs-sharing
          emptyDir: {}
      {{- if .Values.Common.BindingConfigMap }}
        - name: config-volume
          configMap:
            name: {{ .Values.Common.BindingConfigMap }} 
      {{- end }}
      {{- if and .Values.FileBeat.Enable .Values.Tsweb.FileBeatConfigMap }}
        - name: filebeat-config-ts-web
          configMap:
            name: {{ .Values.Tsweb.FileBeatConfigMap }}
      {{- end }}
      containers:
      - name: ts-web
        image: "{{ .Values.Common.ImageRepo }}{{ .Values.Tsweb.Image }}:{{ .Values.Tsweb.Tag }}"
        resources:
          requests:
            cpu: 0.5m
            memory: 256Mi
        env:
        - name: "LICENSE"
          value: "accept"
        {{- if .Values.Common.CommerceVersion }}
        {{- if (or (eq .Values.Common.CommerceVersion "9.0.0.1") (eq .Values.Common.CommerceVersion "9.0.0.0")) }}
          {{- if .Values.Common.OverridePreconfig }}
        - name: "OVERRIDE_PRECONFIG"
          value: {{ .Values.Common.OverridePreconfig | quote }}
          {{- end }}
        {{- end }}
        {{- else }}
        - name: "CONFIGURE_MODE"
          value: {{ .Values.Common.ConfigureMode | quote }}  
        {{- end }}
        - name: "ENVIRONMENT"
          value: {{ .Values.Common.EnvironmentName | quote }}
        - name: "TENANT"
          value: {{ .Values.Common.Tenant | quote }}
        - name: "ENVTYPE"
          value: {{ .Values.Common.EnvironmentType | quote }}
        - name: "DOMAIN_NAME"
          value: "{{ .Values.Common.NameSpace }}.svc.cluster.local"
        - name: "VAULT_CA"
          value: {{ .Values.Common.VaultCA.Enable | quote }}
        {{- if (or (eq .Values.Common.ConfigureMode "Vault") .Values.Common.VaultCA.Enable) }}
        - name: "VAULT_URL"
          value: {{ .Values.Common.VaultURL | quote  }}
        - name: "VAULT_TOKEN"
          value: {{.Values.Common.VaultToken | quote }}
        {{- end }}       
{{- if .Values.Tsweb.EnvParameters }}
     {{- range $key, $value := .Values.Tsweb.EnvParameters }}
        - name: {{ $key | quote }}
          value: {{ $value | quote }}
     {{- end }} 
{{- end }} 
        ports: 
        - containerPort: 8000
          name: port8000
          protocol: TCP
        - containerPort: 8001
          name: port8001
          protocol: TCP
        - containerPort: 8002
          name: port8002
          protocol: TCP
        - containerPort: 8004
          name: port8004
          protocol: TCP
        livenessProbe:
          tcpSocket:
            port: 8000
          initialDelaySeconds: 600
          timeoutSeconds: 300
        volumeMounts:
          - name: logs-sharing
            mountPath: /opt/WebSphere/HTTPServer/logs/container
        {{- if .Values.Common.BindingConfigMap }}
          - name: config-volume
            mountPath: /SETUP/ext-config   
        {{- end }}
{{- if .Values.Tsweb.NodeSelector }}
        nodeSelector:
{{ toYaml .Values.Tsweb.NodeSelector | indent 8 }}
{{- end }}
{{- if .Values.FileBeat.Enable }} 
      - name: filebeat
        image: "{{ .Values.Common.ImageRepo }}{{ .Values.FileBeat.Image }}:{{ .Values.FileBeat.Tag }}"
        args: ["-indexName", "{{ .Values.Common.Tenant }}-{{ .Values.Common.EnvironmentName}}-{{ .Values.Common.EnvironmentType }}", "-targetELK", "{{ .Values.FileBeat.ELKServer }}", "-componentType", "ts-web"]
        volumeMounts:
        - name: logs-sharing
          mountPath: /log
{{- if .Values.Tsweb.FileBeatConfigMap }}
        - name: filebeat-config-ts-web
          mountPath: /etc/filebeat
{{- end }}
{{- end }}
---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.Common.Tenant }}{{ .Values.Common.EnvironmentName}}{{ .Values.Common.EnvironmentType }}{{.Values.Tsweb.Name}}
  labels:
    component: {{ .Values.Common.Tenant }}{{ .Values.Common.EnvironmentName}}{{ .Values.Common.EnvironmentType }}{{.Values.Tsweb.Name}}
  namespace: {{ .Values.Common.NameSpace }} 
spec:
  type: NodePort
  ports:
  - port: 8000
    name: cmc8000
  - port: 8001
    name: acc8001
  - port: 8002
    name: admin8002
  - port: 8004
    name: org8004
  selector:
    component: {{ .Values.Common.Tenant }}{{ .Values.Common.EnvironmentName}}{{ .Values.Common.EnvironmentType }}{{.Values.Tsweb.Name}}
